### ISSUE TITLE
StreamedResponse

### ISSUE THREAD

**Issue by albatrosify** [GoncaloPT/airwatch_socket_workaround#3]
Hello @GoncaloPT,

thanks for your workaround. It shall help me with an internal project.
Is there a way to receive StreamedResponse for File-Downloads? This would really be helpful for bigger or longer file-downloads, to keep the user informed about the status / percentage.

**Comment by albatrosify** [comment]
In general I am unable to download files. As far as I understand the response-type this plugin expects is always a String?

**Comment by GoncaloPT** [comment]
Will have a look into it since I've refactored this inside our project some time ago. I will port the solution to the lib

**Comment by GoncaloPT** [comment]
@albatrosify i've release version 0.0.3. Please test it out to make sure it responds to your use case. Thanks
