### ISSUE TITLE
StreamedResponse

### ISSUE THREAD

**Issue by albatrosify** [GoncaloPT/airwatch_socket_workaround#5]
Hello GoncaloPT,

I am unable to do so on my own, so Id like to ask whether it would be possible to add a StreamedResponse Type Request.
This would be helpful for downloading bigger files and still giving some information about progress to the user.
Also I think the current implementation could run into problems when downloading big files and then sending the bytedata over platform channel at once.

I have 0 idea about Swift and iOS code so I am really struggling to find a solution for this. Could you help with your knowledge?

Best regards and thanks. 🙏

**Comment by GoncaloPT** [comment]
Will look into it

**Comment by GoncaloPT** [comment]
I believe this will make you life easier
